### ISSUE TITLE
Restore from backup (DevOps)

### ISSUE THREAD

**Issue by nniiicc** [QualitativeDataRepository/TechnicalTeam#7]

**Comment by nniiicc** [comment]
Completed on 06.27.2022

Postmortem: 
- Time down = 62 min (from when we went into maintenance until when both Drupal and DV were up)
- Small hicupps
- - Restoration failed with 'restore with no IAM role` and instead used `Restore with original IAM role`  ✅
- - We did not end up changing the DNS because the site is behind a load balancer 
- - Instead we reboot the DNS so that it updates it's hostname and then add it to the load balancer target groups for the main site and annorep  ✅
- - a new production server IP address is generated 
- After taking us out of maintenance we saw a 404
- - Tried restarting payara (did not work) 
- - restarted second time after removing `/usr/local/payara-5.2021.8/glassfish/domains/dataverse/imq/instances/imqbroker/loc` - this worked ✅
- to get Dataverse to connect to solr have to manually run `service solr start` ✅

- Site went through full QA and everything worked at first pass - including recent Dataverse DB changes, and Drupal logins 

- For restoring from backup process - it doesn't make much sense to swtich back over to an "old prod" ... in essence we keep running new prod, and put old prod on ice (aws doesn't charge us if the ec2 is not running) 
- Two implications 
- - We take new prod out of maintenance 
- - If we aren't running an old production instance, how long should we keep it? 

( note all ✅ are places where we need to update disaster recovery documentaiton)

**Comment by adam3smith** [comment]
Check on and likely restart AR-Server for Anno-REP ✅

**Comment by qqmyers** [comment]
FWIW: There isn't any service entry for this yet and no log rotation, etc. The code is in /opt/annorep and the server is started as the counter user right now with:
`java -jar ARServer-0.0.2-SNAPSHOT.jar --server.port=11111 --dataverse.url=https://data.qdr.syr.edu > arlog3.txt &`

**Comment by qqmyers** [comment]
Also FWIW: did a `aws s3 ls qdr-backups` today and verified that the backup files were all created. All but the mysql backup were ~ the same size as yesterday. Downloading the mysql backups and exploring, it looks like the main difference is just fewer entries in cache tables which makes sense since I did do a drush cr to delete the caches yesterday. So - all looks good wr.t. the aws backups.

**Comment by qqmyers** [comment]
One more note for the backup/restore doc: 
/srv/annorep/annorep-env has to be edited to update the ARCORE_SERVER_URL IP address to that of the new instance and then the AR client has to be restarted:
as annorep user:
cd /srv/annorep
DEPLOY_TAG=<8char from commit on desired branch (currently main on prod)> ./deploy
