### ISSUE TITLE
Restore from backup (2nd TT member)

### ISSUE THREAD

**Issue by nniiicc** [QualitativeDataRepository/TechnicalTeam#8]

**Comment by qqmyers** [comment]
History from 09192022 backup/restore:
 cd /usr/local/payara-5.2021.8/glassfish/domains/dataverse/imq/instances/imqbroker
 1989  ls -lA
 1990  rm lock
 1991  service payara restart
 1992  service glassfish-dataverse restart
 1993  cd /srv/glassfish/dataverse/logs
 1994  tail -200 server.log
 1995  curl http://localhost:8080/api/admin/settings
 1996  hostname qdr-prod
 1997  reboot
 1998  sudo bash
 1999  echo "qdr-prod" > /etc/hostname
 2000  reboot
 2001  service glassfish-dataverse restart
 2002  systemctl status glassfish-dataverse.service
 2003  ps -ef
 2004  ps -ef | grep payara
 2005  kill -9 1873
 2006  service glassfish-dataverse restart
 2007  curl http://localhost:8080/api/admin/settings
 2008  service solr start
 2009  cd /opt/annorep
 2010  ls -lA
 2011  java -jar ARServer-0.0.2-SNAPSHOT.jar --server.port=11111 --dataverse.url=https://data.qdr.syr.edu > arlog4.txt &
 2012  cd /srv/annorep
 2013  ls
 2014  vi annorep-env
 2015  su annorep
 2016  cd /opt/annorep
 2017  ps -ef | grep ARS
 2018  kill -9 3669
 2019  su annorep
 2020  ls -lA
 2021  chown -R counter:counter arlog4.txt
 2022  ls -lA
 2023  su annorep
 2024  su counter
 2025  rm /var/www/html/maintenance/maintenance.trigger
 2026  cd /var/www/drupal8
 2027  drush sset system.maintenance_mode 0
 2028  which drush
 2029  ./drush sset system.maintenance_mode 0
 2030  ./drush cr
 curl http://localhost:8080/api/admin/settings
 2033  curl http://localhost:8080/api/admin/settings/:StatusMessageHeader
 2034  curl -X PUT -d ' QDR is transitioning to a model where depositors bear some curation costs. Affiliates of QDR’s institutional members will often be able to deposit free of charge and discounts are available for others. <a href=\"https://qdr.syr.edu/deposit#deposit-fees\">More information here.</a>'  http://localhost:8080/api/admin/settings/:StatusMessageHeader
